### ISSUE TITLE
Support Azure-style connection strings

### ISSUE THREAD

**Issue by atrauzzi** [aloneguid/storage#168]
Requiring the scheme (`azure.blob://`) is fine, but it would be nice if I could drop in whatever Azure or Azure Storage Explorer provide me for connection URIs:

```
DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;
```

(Don't worry, this is just an overblown way to specify the local emulator connection string.)

:smile:

**Comment by ClassTerr** [comment]
Lost 4 hours trying to fix this issue.
What is worked for me is URL-encodeing of the key.
For instance
azure.blob://account=myaccountname;key=VML/PzzivE0DDKvgDLc0OoNHYMRDiUhVqWdUCCHwqhrjkHT700lNLVinBb/ULAAKVc8+OR8zwSMO1xehk7P3/g==
turned into
azure.blob://account=myaccountname;key=VML%2FPzzivE0DDKvgDLc0OoNHYMRDiUhVqWdUCCHwqhrjkHT700lNLVinBb%2FULAAKVc8%2BOR8zwSMO1xehk7P3%2Fg%3D%3D

**Comment by ClassTerr** [comment]
Lost 4 hours trying to fix this issue.
What is worked for me is URL-encoding of the key.
For instance
azure.blob://account=myaccountname;key=VML/PzzivE0DDKvgDLc0OoNHYMRDiUhVqWdUCCHwqhrjkHT700lNLVinBb/ULAAKVc8+OR8zwSMO1xehk7P3/g==
turned into
azure.blob://account=myaccountname;key=VML%2FPzzivE0DDKvgDLc0OoNHYMRDiUhVqWdUCCHwqhrjkHT700lNLVinBb%2FULAAKVc8%2BOR8zwSMO1xehk7P3%2Fg%3D%3D

**Comment by klemmchr** [comment]
The same issue occurs when you want to use a local emulator as the connection string.

```c#
StorageFactory.Blobs.FromConnectionString("azure.blob://UseDevelopmentStorage=true")
```

gives me this exception

```c#
System.ArgumentException: connection string requires 'account' parameter.
         at Storage.Net.ConnectionString.StorageConnectionString.GetRequired(String parameterName, Boolean requireNonEmptyValue, String& value)
         at Storage.Net.Microsoft.Azure.Storage.Blobs.Module.CreateBlobStorage(StorageConnectionString connectionString)
         at Storage.Net.ConnectionString.ConnectionStringFactory.<>c.<CreateBlobStorage>b__4_0(IConnectionFactory factory, StorageConnectionString cs)
         at Storage.Net.ConnectionString.ConnectionStringFactory.<>c__DisplayClass6_0`1.<Create>b__0(IConnectionFactory f)
         at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
         at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
         at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
         at Storage.Net.ConnectionString.ConnectionStringFactory.Create[TInstance](String connectionString, Func`3 createAction)
         at Storage.Net.ConnectionString.ConnectionStringFactory.CreateBlobStorage(String connectionString)
         at Storage.Net.Factory.FromConnectionString(IBlobStorageFactory factory, String connectionString)

```

Why is the library validating an arbitrary connection string? It should make no assumption about the structure of a connection string and instead just pass it to the client library (in this case Azure Blob Storage) and let the validation happen there. The underlying vendor library knows best when a connection string is valid or not.
