### ISSUE TITLE
Azure local development connection string doesn't work

### ISSUE THREAD

**Issue by atrauzzi** [aloneguid/storage#169]
If I follow the documentation [found here](https://github.com/aloneguid/storage/blob/develop/doc/blobs/azure.md), and use `azure.blob://development=true` when calling `FromConnectionString`, I end up with the following exception:

```
System.ArgumentException: connection string requires 'account' parameter.
   at Storage.Net.ConnectionString.StorageConnectionString.GetRequired(String parameterName, Boolean requireNonEmptyValue, String& value)
   at Storage.Net.Microsoft.Azure.Storage.Blobs.Module.CreateBlobStorage(StorageConnectionString connectionString)
   at Storage.Net.ConnectionString.ConnectionStringFactory.<>c.<CreateBlobStorage>b__4_0(IConnectionFactory factory, StorageConnectionString cs)
   at Storage.Net.ConnectionString.ConnectionStringFactory.<>c__DisplayClass6_0`1.<Create>b__0(IConnectionFactory f)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Storage.Net.ConnectionString.ConnectionStringFactory.Create[TInstance](String connectionString, Func`3 createAction)
   at Storage.Net.ConnectionString.ConnectionStringFactory.CreateBlobStorage(String connectionString)
   at Storage.Net.Factory.FromConnectionString(IBlobStorageFactory factory, String connectionString)

```

**Comment by atrauzzi** [comment]
It's still used by many things...

**Comment by Dehalion** [comment]
In current `master` and `develop` branches there is no usage of `` besides its definition (see [Repo search](https://github.com/aloneguid/storage/search?q=UseDevelopmentStorage&unscoped_q=UseDevelopmentStorage).

Which version of Storage.NET do you use and have you tried the new `emu` parameter instead?

**Comment by Dehalion** [comment]
Could you resolve it? If yes it would be great if you could tell us your solution so we could update the documentation if necessary.
