### ISSUE TITLE
FormatException when using Azure Storage with connection string containing "+" character

### ISSUE THREAD

**Issue by ridercz** [aloneguid/storage#238]
I'm trying to use Azure Storage with connection string. The `FromConnectionString` methods throws `FormatException` if the key includes the "+" character. This is the minimal code to reproduce:

> The key was changed before posting this, if course.

```csharp
// Initialize Storage.NET and Azure Blobs
using Storage.Net;
StorageFactory.Modules.UseAzureBlobStorage();

// This does work
var blobStorage = StorageFactory.Blobs.AzureBlobStorageWithSharedKey("myaccountname", "L5oM6w/wdzNH/aoxhssLqky0wp47N0H8pgTWXbgQQl8B2kiUXbe4HUWj22UQe1VmNZhgIuQfbV9j+AStuW8V6Q==");

// This does not
var blobStorage = StorageFactory.Blobs.FromConnectionString("azure.blob://account=myaccountname;key=L5oM6w/wdzNH/aoxhssLqky0wp47N0H8pgTWXbgQQl8B2kiUXbe4HUWj22UQe1VmNZhgIuQfbV9j+AStuW8V6Q==");

// This does work again when "+" was replaced by "X"
var blobStorage = StorageFactory.Blobs.FromConnectionString("azure.blob://account=myaccountname;key=L5oM6w/wdzNH/aoxhssLqky0wp47N0H8pgTWXbgQQl8B2kiUXbe4HUWj22UQe1VmNZhgIuQfbV9jXAStuW8V6Q==");

```

The faulting line results in the following exception:

```
Error: System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Azure.Storage.StorageSharedKeyCredential.SetAccountKey(String accountKey)
   at Azure.Storage.StorageSharedKeyCredential..ctor(String accountName, String accountKey)
   at Storage.Net.Factory.AzureBlobStorageWithSharedKey(IBlobStorageFactory factory, String accountName, String key, Uri serviceUri)
   at Storage.Net.Microsoft.Azure.Storage.Blobs.Module.CreateBlobStorage(StorageConnectionString connectionString)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Storage.Net.ConnectionString.ConnectionStringFactory.Create[TInstance](String connectionString, Func`3 createAction)
   at Storage.Net.ConnectionString.ConnectionStringFactory.CreateBlobStorage(String connectionString)
   at Storage.Net.Factory.FromConnectionString(IBlobStorageFactory factory, String connectionString)
```

The key is (obviously) valid Base-64 value. I discovered that when I use key that does not contain the plus character, it works just fine. I suppose there is some bug in the connection string parsing code that treats `+` as an delimiter or something similar. 

The occurence of this bug is random, as the key is generated by Azure and is random, so it may or may not have contain this character.

**Comment by meta-space** [comment]
Just stumbled over the same issue while deploying asp.net core 6 web app to Azure.

Thanks to your insight, I was able to workaround the bug using the AzureBlobStorageWithSharedKey method for now

**Comment by ridercz** [comment]
This is my workaround:

```cs
var blobConnectionString = builder.Configuration.GetConnectionString("BlobStorage");
if (blobConnectionString.StartsWith("azure.blob://")) {
    var csParts = blobConnectionString[13..].Split(';');
    var account = csParts.Single(x => x.StartsWith("account="))[8..];
    var key = csParts.Single(x => x.StartsWith("key="))[4..];
    builder.Services.AddTransient<IBlobStorage>(s => StorageFactory.Blobs.AzureBlobStorageWithSharedKey(account, key));
} else {
    builder.Services.AddTransient(s => StorageFactory.Blobs.FromConnectionString(blobConnectionString));
}
```

**Comment by cjbush** [comment]
I believe this is a duplicate of #173. There's a workaround mentioned on there that you can URL encode your connection string to get around the problem (ie replace the '+' with a '%2B' since '+' represents a space in a URL)
